AssystJournal/Controllers/CommentController.cs
using AssystJournal.Models;
using AssystJournal.WebApi.Controllers;
using System.Net;
using System.Web.Mvc;

namespace AssystJournal.Controllers
{
    public class CommentController : Controller
    {
        private AssystCommentController assystComment = new AssystCommentController();

        [HttpGet]
        public ActionResult Create(int id)
        { 
            ViewBag.H2 = "Добавить комментарий";
            return View(new Comment() { Journal = new Journal() { Id = id } });
        }

        [HttpPost]
        public ActionResult Create(Comment comment)
        {
            ViewBag.H2 = "Добавить комментарий";
            assystComment.Post(comment);
            return RedirectToAction("Details", "Journal", new { id = comment.Journal.Id });
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ViewBag.H2 = "Изменить комментарий";
            return View(assystComment.Find((int)id));
        }

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            ViewBag.H2 = "Изменить комментарий";
            if (comment == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            assystComment.Put(comment);
            return RedirectToAction("Details", "Journal", new { id = comment.Journal.Id });
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(assystComment.Find((int)id));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, int journalId)
        {
            assystComment.Delete(id);
            return RedirectToAction("Details", "Journal", new { id = journalId });   
        }      
    }
}

AssystJournal/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AssystJournal.Controllers
{
    public class HomeController : Controller
    { 
        public ActionResult About()
        {
            ViewBag.Message = "Краткая сводка по приложению";
            return View();
        }        
    }
}

AssystJournal/Controllers/JournalController.cs
using AssystJournal.Models;
using AssystJournal.WebApi.Controllers;
using System;
using System.Net;
using System.Web.Mvc;

namespace AssystJournal.Controllers
{
    public class JournalController : Controller
    {
        private AssystJournalController assystJournal = new AssystJournalController();

        public ActionResult Index()
        {
            return View(assystJournal.Get(null, null));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.H2 = "Добавить запись в журнал";
            var journal = new Journal();
                journal.Date = DateTime.Now;
            return View(journal);
        }

        public ActionResult ControlRequest()
        {
            ViewBag.Message = "Ваши обращения, которые вы контролируете";
            return View("Index", assystJournal.Get(new FilteringJournal(isOnControl: true), null));
        }

        [HttpPost]
        public ActionResult Create(Journal journal)
        {
            ViewBag.H2 = "Добавить запись в журнал";
            assystJournal.Post(journal);
            return Redirect("/");
        }
      
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.H2 = "Просмотр записи в журнале";
            return View(assystJournal.Find((int)id));
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(assystJournal.Find((int)id));
        }

        [HttpPost]
        public ActionResult Edit(Journal journal)
        {
            ViewBag.H2 = "Изменить запись в журнале";

            if (journal == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            assystJournal.Put(journal);
            return Redirect("/");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                      
            return View(assystJournal.Find((int)id));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            assystJournal.Delete(id);
            return Redirect("/");
        }       
    }
}

AssystJournal/Views/Comment/Create.cshtml
@{
    ViewBag.Title = "Создать";
}

@model AssystJournal.Models.Comment
<h2>@ViewBag.H2</h2>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Journal.Id)     
        <div class="item">
            @Html.LabelFor(model => model.Text, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text)
                @Html.ValidationMessageFor(model => model.Text)
            </div>
        </div>
        <input type="submit" value="Отправить" />
    }
</div>

AssystJournal/Views/Comment/Delete.cshtml
@model AssystJournal.Models.Comment
@{
    ViewBag.Title = "Удалить";
}

<h2>Удалить</h2>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Date)</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd>
        <dt>@Html.DisplayNameFor(model => model.Text)</dt>
        <dd>@Html.DisplayFor(model => model.Text)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" />         
        </div>
    }
</div>

AssystJournal/Views/Comment/Edit.cshtml
@{
    ViewBag.Title = "Редактировать";
}

@model AssystJournal.Models.Comment
<h2>@ViewBag.H2</h2>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Journal.Id)
 
        <div class="item">
            @Html.LabelFor(model => model.Text, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text)
                @Html.ValidationMessageFor(model => model.Text)
            </div>
        </div>
        <input type="submit" value="Отправить" />
    }
</div>

AssystJournal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Система предназначена для введения списка обработанных поручений</p>

AssystJournal/Views/Journal/Create.cshtml
@{
    ViewBag.Title = "Создать";
}
@model AssystJournal.Models.Journal
<h2>@ViewBag.H2</h2>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date)         
                    @Html.ValidationMessageFor(model => model.Date)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AssystId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AssystId)
                    @Html.ValidationMessageFor(model => model.AssystId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClientId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClientId)
                    @Html.ValidationMessageFor(model => model.ClientId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Decription, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Decription)
                    @Html.ValidationMessageFor(model => model.Decription)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Result)
                    @Html.ValidationMessageFor(model => model.Result)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsOnControl, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.IsOnControl)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Отправить" class="btn btn-default" />
                </div>
            </div>

        </div>
    }
</div>

AssystJournal/Views/Journal/Delete.cshtml
@model AssystJournal.Models.Journal
@{
    ViewBag.Title = "Удалить";
}

<h2>Удалить</h2>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Date)</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd>
        <dt>@Html.DisplayNameFor(model => model.AssystId)</dt>
        <dd>@Html.DisplayFor(model => model.AssystId)</dd>
        <dt>@Html.DisplayNameFor(model => model.ClientId)</dt>
        <dd>@Html.DisplayFor(model => model.ClientId)</dd>
        <dt>@Html.DisplayNameFor(model => model.Decription)</dt>
        <dd>@Html.DisplayFor(model => model.Decription)</dd>
        <dt>@Html.DisplayNameFor(model => model.Result)</dt>
        <dd>@Html.DisplayFor(model => model.Result)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" />
            <br />
            <br />
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

AssystJournal/Views/Journal/Details.cshtml
@using AssystJournal.Models
@{
    ViewBag.Title = "Просмотр";
}

@model Journal
@{ Comment dummyModel = null; }

<h2>@ViewBag.H2</h2>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Date)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AssystId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.AssystId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClientId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.ClientId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Decription, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Decription)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Result)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsOnControl, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.IsOnControl)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Отправить" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>


<div class="row">
    @Html.ActionLink("Добавить комментарий", "Create", "Comment", new { id = Model.Id }, null)
</div>

@if (Model.Comments != null && Model.Comments.Count > 0)
{
    <div class="row top-buffer">
        <table class="table-bordered">
            <tr>
                <th></th>
                <th class="text-center">@Html.DisplayNameFor(model => dummyModel.Id)</th>
                <th class="text-center">@Html.DisplayNameFor(model => dummyModel.Date)</th>
                <th class="text-center">@Html.DisplayNameFor(model => dummyModel.Text)</th>
                <th></th>
            </tr>


            @foreach (var item in Model.Comments)
                {
                <tr>
                    <td class="text-center">@Html.ActionLink("Изменить", "Edit", "Comment", new { id = item.Id }, null)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Id)</td>              
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Date)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Text)</td>
                    <td class="text-center">@Html.ActionLink("Удалить", "Delete", "Comment", new { id = item.Id }, null)</td>
                </tr>
            }

        </table>
    </div>
}

AssystJournal/Views/Journal/Edit.cshtml
@{
    ViewBag.Title = "Создать";
}
@model AssystJournal.Models.Journal
@{AssystJournal.Models.Comment dummyModel = null; }
<h2>@ViewBag.H2</h2>

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date)
                    @Html.ValidationMessageFor(model => model.Date)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AssystId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AssystId)
                    @Html.ValidationMessageFor(model => model.AssystId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ClientId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClientId)
                    @Html.ValidationMessageFor(model => model.ClientId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Decription, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Decription)
                    @Html.ValidationMessageFor(model => model.Decription)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Result)
                    @Html.ValidationMessageFor(model => model.Result)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IsOnControl, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.IsOnControl)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Отправить" class="btn btn-default" />
                </div>
            </div>

        </div>
    }
</div>

<div class="row">
    @Html.ActionLink("Добавить комментарий", "Create", "Comment", new { id = Model.Id }, null)
</div>

@if (Model.Comments != null && Model.Comments.Count > 0)
{
    <div class="row top-buffer">
        <table class="table-bordered">
            <tr>
                <th></th>
                <th class="text-center">@Html.DisplayNameFor(model => dummyModel.Id)</th>
                <th class="text-center">@Html.DisplayNameFor(model => dummyModel.Date)</th>
                <th class="text-center">@Html.DisplayNameFor(model => dummyModel.Text)</th>
                <th></th>
            </tr>
            @foreach (var item in Model.Comments)
            {
                <tr>
                    <td class="text-center">@Html.ActionLink("Изменить", "Edit", "Comment", new { id = item.Id }, null)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Id)</td>                
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Date)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.Text)</td>
                    <td class="text-center">@Html.ActionLink("Удалить", "Delete", "Comment", new { id = item.Id }, null)</td>
                </tr>
            }
        </table>
    </div>
}

AssystJournal/Views/Journal/Index.cshtml
@{
    ViewBag.Title = "Обращения";
}
@model  IEnumerable<AssystJournal.Models.Journal>


<h1>Спиоск обращений</h1>
<h3>@ViewBag.Message</h3>


<div class="row">
    <table class="table-bordered">
        <tr>
            <th></th>
            <th class="text-center">@Html.DisplayNameFor(model => model.Id)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.Date)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.AssystId)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.ClientId)</th>
            <th>@Html.DisplayNameFor(model => model.Decription)</th>
            <th>@Html.DisplayNameFor(model => model.Result)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.Comments)</th>
            <th class="text-center">@Html.DisplayNameFor(model => model.IsOnControl)</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr class="@(item.IsOnControl ? "warning" : "")">
                <td class="text-center">@Html.ActionLink("Изменить", "Edit", new { id = item.Id }) | @Html.ActionLink("Просмотреть", "Details", new { id = item.Id })</td>
                <td class="text-center">@Html.DisplayFor(modelItem => item.Id)</td>
                <td class="text-center">@Html.DisplayFor(modelItem => item.Date)</td>
                <td class="text-center">@Html.DisplayFor(modelItem => item.AssystId)</td>
                <td class="text-center">@Html.DisplayFor(modelItem => item.ClientId)</td>
                <td>@Html.DisplayFor(modelItem => item.Decription)</td>
                <td>@Html.DisplayFor(modelItem => item.Result)</td>
                <td class="text-center">@Html.DisplayFor(modelItem => item.Comments.Count)</td>
                <td class="text-center">@Html.DisplayFor(modelItem => item.IsOnControl)</td>
                <td class="text-center">@Html.ActionLink("Удалить", "Delete",new { id = item.Id }) | @Html.ActionLink("Добавить. комментарий", "Create", "Comment", new { id = item.Id }, null)</td>
            </tr>
        }

    </table>
</div>

AssystJournal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Обращения", "Index", "Journal")</li>
                    <li>@Html.ActionLink("На контроле", "ControlRequest", "Journal")</li>
                    <li>@Html.ActionLink("Добавить", "Create", "Journal")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>